// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DMService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::LocofsRpc;

class DMServiceHandler : virtual public DMServiceIf {
 public:
  DMServiceHandler() {
    // Your initialization goes here
  }

  int32_t mkdir(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("mkdir\n");
  }

  int32_t access(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("access\n");
  }

  int32_t chown(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("chown\n");
  }

  int32_t chmod(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("chmod\n");
  }

  int32_t rmdir(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("rmdir\n");
  }

  int32_t rename(const std::string& old_path, const std::string& new_path) {
    // Your implementation goes here
    printf("rename\n");
  }

  void getAttr(DirectoryInode& _return, const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("getAttr\n");
  }

  void readdir(std::string& _return, const std::string& path) {
    // Your implementation goes here
    printf("readdir\n");
  }

  int32_t opendir(const std::string& path, const DirectoryInode& di) {
    // Your implementation goes here
    printf("opendir\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DMServiceHandler> handler(new DMServiceHandler());
  shared_ptr<TProcessor> processor(new DMServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

