/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LocofsRpc_CONSTANTS_H
#define LocofsRpc_CONSTANTS_H

#include "LocofsRpc_types.h"

namespace LocofsRpc {

class LocofsRpcConstants {
 public:
  LocofsRpcConstants();

};

extern const LocofsRpcConstants g_LocofsRpc_constants;

} // namespace

#endif
