/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LocofsRpc_constants.h"

namespace LocofsRpc {

const LocofsRpcConstants g_LocofsRpc_constants;

LocofsRpcConstants::LocofsRpcConstants() {
}

} // namespace

